name: Build, Run and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        env:
          cache-name: cache
          with:
          path: .
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: sudo apt-get -y install gfortran
      - run: sudo apt-get -y install build-essential;
      - run: sudo apt -y update
      - run: sudo apt -y upgrade
      - run: sudo apt-get -y install tree
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: tree
      - run: cd model/runs/default; ls; make local
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: cd model; python golden_test.py
