name: Build, run and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: model
      run: 
        cd model
        ls
        pwd
    - name: make
      run: make
